// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
typedef void (*UniffiForeignFutureDroppedCallback)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
typedef uint64_t (*UniffiCallbackInterfaceClone)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
typedef struct UniffiForeignFutureDroppedCallbackStruct {
    uint64_t handle;
    UniffiForeignFutureDroppedCallback _Nonnull free;
} UniffiForeignFutureDroppedCallbackStruct;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
typedef struct UniffiForeignFutureResultU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureResultU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
typedef struct UniffiForeignFutureResultI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureResultI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
typedef struct UniffiForeignFutureResultU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureResultU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
typedef struct UniffiForeignFutureResultI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureResultI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
typedef struct UniffiForeignFutureResultU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureResultU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
typedef struct UniffiForeignFutureResultI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureResultI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
typedef struct UniffiForeignFutureResultU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureResultU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
typedef struct UniffiForeignFutureResultI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureResultI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
typedef struct UniffiForeignFutureResultF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureResultF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
typedef struct UniffiForeignFutureResultF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureResultF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
typedef struct UniffiForeignFutureResultRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureResultRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
typedef struct UniffiForeignFutureResultVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureResultVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureResultVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_DESKTOP_DELEGATE_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_DESKTOP_DELEGATE_METHOD0
typedef void (*UniffiCallbackInterfaceDesktopDelegateMethod0)(uint64_t, uint64_t, uint32_t, uint32_t, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_DESKTOP_DELEGATE_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_DESKTOP_DELEGATE_METHOD1
typedef void (*UniffiCallbackInterfaceDesktopDelegateMethod1)(uint64_t, uint32_t, uint32_t, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_DESKTOP_DELEGATE_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_DESKTOP_DELEGATE_METHOD2
typedef void (*UniffiCallbackInterfaceDesktopDelegateMethod2)(uint64_t, uint64_t, double, double, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_DESKTOP_DELEGATE_METHOD3
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_DESKTOP_DELEGATE_METHOD3
typedef void (*UniffiCallbackInterfaceDesktopDelegateMethod3)(uint64_t, uint64_t, uint32_t, int8_t, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_DESKTOP_DELEGATE_METHOD4
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_DESKTOP_DELEGATE_METHOD4
typedef void (*UniffiCallbackInterfaceDesktopDelegateMethod4)(uint64_t, uint64_t, uint32_t, int8_t, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_DESKTOP_DELEGATE_METHOD5
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_DESKTOP_DELEGATE_METHOD5
typedef void (*UniffiCallbackInterfaceDesktopDelegateMethod5)(uint64_t, uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_DESKTOP_DELEGATE_METHOD6
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_DESKTOP_DELEGATE_METHOD6
typedef void (*UniffiCallbackInterfaceDesktopDelegateMethod6)(uint64_t, uint64_t, double, double, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_DESKTOP_DELEGATE_METHOD7
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_DESKTOP_DELEGATE_METHOD7
typedef void (*UniffiCallbackInterfaceDesktopDelegateMethod7)(uint64_t, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_DESKTOP_DELEGATE
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_DESKTOP_DELEGATE
typedef struct UniffiVTableCallbackInterfaceDesktopDelegate {
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
    UniffiCallbackInterfaceClone _Nonnull uniffiClone;
    UniffiCallbackInterfaceDesktopDelegateMethod0 _Nonnull onFrame;
    UniffiCallbackInterfaceDesktopDelegateMethod1 _Nonnull onCompositeFrame;
    UniffiCallbackInterfaceDesktopDelegateMethod2 _Nonnull onPointerMove;
    UniffiCallbackInterfaceDesktopDelegateMethod3 _Nonnull onPointerButton;
    UniffiCallbackInterfaceDesktopDelegateMethod4 _Nonnull onKey;
    UniffiCallbackInterfaceDesktopDelegateMethod5 _Nonnull onKeyChar;
    UniffiCallbackInterfaceDesktopDelegateMethod6 _Nonnull onScroll;
    UniffiCallbackInterfaceDesktopDelegateMethod7 _Nonnull wallpaperPath;
} UniffiVTableCallbackInterfaceDesktopDelegate;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_FN_CLONE_DESKTOPENGINE
#define UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_FN_CLONE_DESKTOPENGINE
uint64_t uniffi_clone_engine_fn_clone_desktopengine(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_FN_FREE_DESKTOPENGINE
#define UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_FN_FREE_DESKTOPENGINE
void uniffi_clone_engine_fn_free_desktopengine(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_FN_CONSTRUCTOR_DESKTOPENGINE_NEW
#define UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_FN_CONSTRUCTOR_DESKTOPENGINE_NEW
uint64_t uniffi_clone_engine_fn_constructor_desktopengine_new(uint64_t delegate, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_FN_METHOD_DESKTOPENGINE_DRAW_FRAME
#define UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_FN_METHOD_DESKTOPENGINE_DRAW_FRAME
void uniffi_clone_engine_fn_method_desktopengine_draw_frame(uint64_t ptr, uint64_t surface_texture_view_hack, uint32_t width, uint32_t height, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_FN_METHOD_DESKTOPENGINE_GET_COMMANDS
#define UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_FN_METHOD_DESKTOPENGINE_GET_COMMANDS
RustBuffer uniffi_clone_engine_fn_method_desktopengine_get_commands(uint64_t ptr, uint32_t width, uint32_t height, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_FN_INIT_CALLBACK_VTABLE_DESKTOPDELEGATE
#define UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_FN_INIT_CALLBACK_VTABLE_DESKTOPDELEGATE
void uniffi_clone_engine_fn_init_callback_vtable_desktopdelegate(const UniffiVTableCallbackInterfaceDesktopDelegate* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_FN_FUNC_RUN_DESKTOP
#define UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_FN_FUNC_RUN_DESKTOP
void uniffi_clone_engine_fn_func_run_desktop(uint64_t delegate, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUSTBUFFER_ALLOC
RustBuffer ffi_clone_engine_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_clone_engine_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUSTBUFFER_FREE
void ffi_clone_engine_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUSTBUFFER_RESERVE
RustBuffer ffi_clone_engine_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_POLL_U8
void ffi_clone_engine_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_CANCEL_U8
void ffi_clone_engine_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_FREE_U8
void ffi_clone_engine_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_clone_engine_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_POLL_I8
void ffi_clone_engine_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_CANCEL_I8
void ffi_clone_engine_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_FREE_I8
void ffi_clone_engine_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_COMPLETE_I8
int8_t ffi_clone_engine_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_POLL_U16
void ffi_clone_engine_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_CANCEL_U16
void ffi_clone_engine_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_FREE_U16
void ffi_clone_engine_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_clone_engine_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_POLL_I16
void ffi_clone_engine_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_CANCEL_I16
void ffi_clone_engine_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_FREE_I16
void ffi_clone_engine_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_COMPLETE_I16
int16_t ffi_clone_engine_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_POLL_U32
void ffi_clone_engine_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_CANCEL_U32
void ffi_clone_engine_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_FREE_U32
void ffi_clone_engine_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_clone_engine_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_POLL_I32
void ffi_clone_engine_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_CANCEL_I32
void ffi_clone_engine_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_FREE_I32
void ffi_clone_engine_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_COMPLETE_I32
int32_t ffi_clone_engine_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_POLL_U64
void ffi_clone_engine_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_CANCEL_U64
void ffi_clone_engine_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_FREE_U64
void ffi_clone_engine_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_clone_engine_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_POLL_I64
void ffi_clone_engine_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_CANCEL_I64
void ffi_clone_engine_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_FREE_I64
void ffi_clone_engine_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_COMPLETE_I64
int64_t ffi_clone_engine_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_POLL_F32
void ffi_clone_engine_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_CANCEL_F32
void ffi_clone_engine_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_FREE_F32
void ffi_clone_engine_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_COMPLETE_F32
float ffi_clone_engine_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_POLL_F64
void ffi_clone_engine_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_CANCEL_F64
void ffi_clone_engine_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_FREE_F64
void ffi_clone_engine_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_COMPLETE_F64
double ffi_clone_engine_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_clone_engine_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_clone_engine_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_clone_engine_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_clone_engine_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_POLL_VOID
void ffi_clone_engine_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_CANCEL_VOID
void ffi_clone_engine_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_FREE_VOID
void ffi_clone_engine_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_RUST_FUTURE_COMPLETE_VOID
void ffi_clone_engine_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_CHECKSUM_FUNC_RUN_DESKTOP
#define UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_CHECKSUM_FUNC_RUN_DESKTOP
uint16_t uniffi_clone_engine_checksum_func_run_desktop(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_CHECKSUM_METHOD_DESKTOPENGINE_DRAW_FRAME
#define UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_CHECKSUM_METHOD_DESKTOPENGINE_DRAW_FRAME
uint16_t uniffi_clone_engine_checksum_method_desktopengine_draw_frame(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_CHECKSUM_METHOD_DESKTOPENGINE_GET_COMMANDS
#define UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_CHECKSUM_METHOD_DESKTOPENGINE_GET_COMMANDS
uint16_t uniffi_clone_engine_checksum_method_desktopengine_get_commands(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_CHECKSUM_CONSTRUCTOR_DESKTOPENGINE_NEW
#define UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_CHECKSUM_CONSTRUCTOR_DESKTOPENGINE_NEW
uint16_t uniffi_clone_engine_checksum_constructor_desktopengine_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_CHECKSUM_METHOD_DESKTOPDELEGATE_ON_FRAME
#define UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_CHECKSUM_METHOD_DESKTOPDELEGATE_ON_FRAME
uint16_t uniffi_clone_engine_checksum_method_desktopdelegate_on_frame(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_CHECKSUM_METHOD_DESKTOPDELEGATE_ON_COMPOSITE_FRAME
#define UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_CHECKSUM_METHOD_DESKTOPDELEGATE_ON_COMPOSITE_FRAME
uint16_t uniffi_clone_engine_checksum_method_desktopdelegate_on_composite_frame(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_CHECKSUM_METHOD_DESKTOPDELEGATE_ON_POINTER_MOVE
#define UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_CHECKSUM_METHOD_DESKTOPDELEGATE_ON_POINTER_MOVE
uint16_t uniffi_clone_engine_checksum_method_desktopdelegate_on_pointer_move(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_CHECKSUM_METHOD_DESKTOPDELEGATE_ON_POINTER_BUTTON
#define UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_CHECKSUM_METHOD_DESKTOPDELEGATE_ON_POINTER_BUTTON
uint16_t uniffi_clone_engine_checksum_method_desktopdelegate_on_pointer_button(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_CHECKSUM_METHOD_DESKTOPDELEGATE_ON_KEY
#define UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_CHECKSUM_METHOD_DESKTOPDELEGATE_ON_KEY
uint16_t uniffi_clone_engine_checksum_method_desktopdelegate_on_key(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_CHECKSUM_METHOD_DESKTOPDELEGATE_ON_KEY_CHAR
#define UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_CHECKSUM_METHOD_DESKTOPDELEGATE_ON_KEY_CHAR
uint16_t uniffi_clone_engine_checksum_method_desktopdelegate_on_key_char(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_CHECKSUM_METHOD_DESKTOPDELEGATE_ON_SCROLL
#define UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_CHECKSUM_METHOD_DESKTOPDELEGATE_ON_SCROLL
uint16_t uniffi_clone_engine_checksum_method_desktopdelegate_on_scroll(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_CHECKSUM_METHOD_DESKTOPDELEGATE_WALLPAPER_PATH
#define UNIFFI_FFIDEF_UNIFFI_CLONE_ENGINE_CHECKSUM_METHOD_DESKTOPDELEGATE_WALLPAPER_PATH
uint16_t uniffi_clone_engine_checksum_method_desktopdelegate_wallpaper_path(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_ENGINE_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_CLONE_ENGINE_UNIFFI_CONTRACT_VERSION
uint32_t ffi_clone_engine_uniffi_contract_version(void
    
);
#endif

// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
typedef void (*UniffiForeignFutureDroppedCallback)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
typedef uint64_t (*UniffiCallbackInterfaceClone)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
typedef struct UniffiForeignFutureDroppedCallbackStruct {
    uint64_t handle;
    UniffiForeignFutureDroppedCallback _Nonnull free;
} UniffiForeignFutureDroppedCallbackStruct;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
typedef struct UniffiForeignFutureResultU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureResultU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
typedef struct UniffiForeignFutureResultI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureResultI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
typedef struct UniffiForeignFutureResultU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureResultU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
typedef struct UniffiForeignFutureResultI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureResultI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
typedef struct UniffiForeignFutureResultU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureResultU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
typedef struct UniffiForeignFutureResultI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureResultI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
typedef struct UniffiForeignFutureResultU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureResultU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
typedef struct UniffiForeignFutureResultI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureResultI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
typedef struct UniffiForeignFutureResultF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureResultF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
typedef struct UniffiForeignFutureResultF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureResultF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
typedef struct UniffiForeignFutureResultRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureResultRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
typedef struct UniffiForeignFutureResultVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureResultVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureResultVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_FN_CLONE_APPRENDERER
#define UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_FN_CLONE_APPRENDERER
uint64_t uniffi_clone_render_fn_clone_apprenderer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_FN_FREE_APPRENDERER
#define UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_FN_FREE_APPRENDERER
void uniffi_clone_render_fn_free_apprenderer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_FN_CONSTRUCTOR_APPRENDERER_NEW
#define UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_FN_CONSTRUCTOR_APPRENDERER_NEW
uint64_t uniffi_clone_render_fn_constructor_apprenderer_new(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_FN_METHOD_APPRENDERER_IOSURFACE_ID
#define UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_FN_METHOD_APPRENDERER_IOSURFACE_ID
uint32_t uniffi_clone_render_fn_method_apprenderer_iosurface_id(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_FN_METHOD_APPRENDERER_MACH_PORT
#define UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_FN_METHOD_APPRENDERER_MACH_PORT
uint32_t uniffi_clone_render_fn_method_apprenderer_mach_port(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_FN_METHOD_APPRENDERER_MACH_PORT_AT
#define UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_FN_METHOD_APPRENDERER_MACH_PORT_AT
uint32_t uniffi_clone_render_fn_method_apprenderer_mach_port_at(uint64_t ptr, uint32_t index, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_FN_METHOD_APPRENDERER_RENDER
#define UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_FN_METHOD_APPRENDERER_RENDER
uint32_t uniffi_clone_render_fn_method_apprenderer_render(uint64_t ptr, RustBuffer commands, uint32_t width, uint32_t height, float scale, int8_t transparent, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_FN_METHOD_APPRENDERER_RENDER_TO_PIXELS
#define UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_FN_METHOD_APPRENDERER_RENDER_TO_PIXELS
RustBuffer uniffi_clone_render_fn_method_apprenderer_render_to_pixels(uint64_t ptr, RustBuffer commands, uint32_t width, uint32_t height, float scale, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_FN_METHOD_APPRENDERER_RENDER_TO_PIXELS_TRANSPARENT
#define UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_FN_METHOD_APPRENDERER_RENDER_TO_PIXELS_TRANSPARENT
RustBuffer uniffi_clone_render_fn_method_apprenderer_render_to_pixels_transparent(uint64_t ptr, RustBuffer commands, uint32_t width, uint32_t height, float scale, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_FN_METHOD_APPRENDERER_TAKE_TEXTURES_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_FN_METHOD_APPRENDERER_TAKE_TEXTURES_CHANGED
int8_t uniffi_clone_render_fn_method_apprenderer_take_textures_changed(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUSTBUFFER_ALLOC
RustBuffer ffi_clone_render_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_clone_render_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUSTBUFFER_FREE
void ffi_clone_render_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUSTBUFFER_RESERVE
RustBuffer ffi_clone_render_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_POLL_U8
void ffi_clone_render_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_CANCEL_U8
void ffi_clone_render_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_FREE_U8
void ffi_clone_render_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_clone_render_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_POLL_I8
void ffi_clone_render_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_CANCEL_I8
void ffi_clone_render_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_FREE_I8
void ffi_clone_render_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_COMPLETE_I8
int8_t ffi_clone_render_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_POLL_U16
void ffi_clone_render_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_CANCEL_U16
void ffi_clone_render_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_FREE_U16
void ffi_clone_render_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_clone_render_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_POLL_I16
void ffi_clone_render_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_CANCEL_I16
void ffi_clone_render_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_FREE_I16
void ffi_clone_render_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_COMPLETE_I16
int16_t ffi_clone_render_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_POLL_U32
void ffi_clone_render_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_CANCEL_U32
void ffi_clone_render_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_FREE_U32
void ffi_clone_render_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_clone_render_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_POLL_I32
void ffi_clone_render_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_CANCEL_I32
void ffi_clone_render_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_FREE_I32
void ffi_clone_render_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_COMPLETE_I32
int32_t ffi_clone_render_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_POLL_U64
void ffi_clone_render_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_CANCEL_U64
void ffi_clone_render_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_FREE_U64
void ffi_clone_render_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_clone_render_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_POLL_I64
void ffi_clone_render_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_CANCEL_I64
void ffi_clone_render_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_FREE_I64
void ffi_clone_render_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_COMPLETE_I64
int64_t ffi_clone_render_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_POLL_F32
void ffi_clone_render_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_CANCEL_F32
void ffi_clone_render_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_FREE_F32
void ffi_clone_render_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_COMPLETE_F32
float ffi_clone_render_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_POLL_F64
void ffi_clone_render_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_CANCEL_F64
void ffi_clone_render_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_FREE_F64
void ffi_clone_render_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_COMPLETE_F64
double ffi_clone_render_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_clone_render_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_clone_render_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_clone_render_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_clone_render_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_POLL_VOID
void ffi_clone_render_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_CANCEL_VOID
void ffi_clone_render_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_FREE_VOID
void ffi_clone_render_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_RUST_FUTURE_COMPLETE_VOID
void ffi_clone_render_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_CHECKSUM_METHOD_APPRENDERER_IOSURFACE_ID
#define UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_CHECKSUM_METHOD_APPRENDERER_IOSURFACE_ID
uint16_t uniffi_clone_render_checksum_method_apprenderer_iosurface_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_CHECKSUM_METHOD_APPRENDERER_MACH_PORT
#define UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_CHECKSUM_METHOD_APPRENDERER_MACH_PORT
uint16_t uniffi_clone_render_checksum_method_apprenderer_mach_port(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_CHECKSUM_METHOD_APPRENDERER_MACH_PORT_AT
#define UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_CHECKSUM_METHOD_APPRENDERER_MACH_PORT_AT
uint16_t uniffi_clone_render_checksum_method_apprenderer_mach_port_at(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_CHECKSUM_METHOD_APPRENDERER_RENDER
#define UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_CHECKSUM_METHOD_APPRENDERER_RENDER
uint16_t uniffi_clone_render_checksum_method_apprenderer_render(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_CHECKSUM_METHOD_APPRENDERER_RENDER_TO_PIXELS
#define UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_CHECKSUM_METHOD_APPRENDERER_RENDER_TO_PIXELS
uint16_t uniffi_clone_render_checksum_method_apprenderer_render_to_pixels(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_CHECKSUM_METHOD_APPRENDERER_RENDER_TO_PIXELS_TRANSPARENT
#define UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_CHECKSUM_METHOD_APPRENDERER_RENDER_TO_PIXELS_TRANSPARENT
uint16_t uniffi_clone_render_checksum_method_apprenderer_render_to_pixels_transparent(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_CHECKSUM_METHOD_APPRENDERER_TAKE_TEXTURES_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_CHECKSUM_METHOD_APPRENDERER_TAKE_TEXTURES_CHANGED
uint16_t uniffi_clone_render_checksum_method_apprenderer_take_textures_changed(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_CHECKSUM_CONSTRUCTOR_APPRENDERER_NEW
#define UNIFFI_FFIDEF_UNIFFI_CLONE_RENDER_CHECKSUM_CONSTRUCTOR_APPRENDERER_NEW
uint16_t uniffi_clone_render_checksum_constructor_apprenderer_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CLONE_RENDER_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_CLONE_RENDER_UNIFFI_CONTRACT_VERSION
uint32_t ffi_clone_render_uniffi_contract_version(void
    
);
#endif

