// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(clone_audioFFI)
import clone_audioFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_clone_audio_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_clone_audio_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureCloneAudioInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol AudioOutputStreamProtocol: AnyObject, Sendable {
    
    func channels()  -> UInt16
    
    func isPlaying()  -> Bool
    
    func pause() 
    
    func play() 
    
    func sampleRate()  -> UInt32
    
    func setVolume(volume: Float) 
    
    func stop() 
    
    func volume()  -> Float
    
    /**
     * Push interleaved f32 samples into the ring buffer.
     * Returns the number of samples actually written (may be less than
     * input length if the buffer is full — caller should retry).
     */
    func write(samples: [Float])  -> UInt32
    
}
open class AudioOutputStream: AudioOutputStreamProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_clone_audio_fn_clone_audiooutputstream(self.handle, $0) }
    }
    /**
     * Create a new PCM output stream.
     * Audio won't play until `play()` is called.
     */
public convenience init(sampleRate: UInt32, channels: UInt16)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeAudioError_lift) {
    uniffi_clone_audio_fn_constructor_audiooutputstream_new(
        FfiConverterUInt32.lower(sampleRate),
        FfiConverterUInt16.lower(channels),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_clone_audio_fn_free_audiooutputstream(handle, $0) }
    }

    

    
open func channels() -> UInt16  {
    return try!  FfiConverterUInt16.lift(try! rustCall() {
    uniffi_clone_audio_fn_method_audiooutputstream_channels(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func isPlaying() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_clone_audio_fn_method_audiooutputstream_is_playing(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func pause()  {try! rustCall() {
    uniffi_clone_audio_fn_method_audiooutputstream_pause(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func play()  {try! rustCall() {
    uniffi_clone_audio_fn_method_audiooutputstream_play(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func sampleRate() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_clone_audio_fn_method_audiooutputstream_sample_rate(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func setVolume(volume: Float)  {try! rustCall() {
    uniffi_clone_audio_fn_method_audiooutputstream_set_volume(
            self.uniffiCloneHandle(),
        FfiConverterFloat.lower(volume),$0
    )
}
}
    
open func stop()  {try! rustCall() {
    uniffi_clone_audio_fn_method_audiooutputstream_stop(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func volume() -> Float  {
    return try!  FfiConverterFloat.lift(try! rustCall() {
    uniffi_clone_audio_fn_method_audiooutputstream_volume(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Push interleaved f32 samples into the ring buffer.
     * Returns the number of samples actually written (may be less than
     * input length if the buffer is full — caller should retry).
     */
open func write(samples: [Float]) -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_clone_audio_fn_method_audiooutputstream_write(
            self.uniffiCloneHandle(),
        FfiConverterSequenceFloat.lower(samples),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAudioOutputStream: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = AudioOutputStream

    public static func lift(_ handle: UInt64) throws -> AudioOutputStream {
        return AudioOutputStream(unsafeFromHandle: handle)
    }

    public static func lower(_ value: AudioOutputStream) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AudioOutputStream {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: AudioOutputStream, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAudioOutputStream_lift(_ handle: UInt64) throws -> AudioOutputStream {
    return try FfiConverterTypeAudioOutputStream.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAudioOutputStream_lower(_ value: AudioOutputStream) -> UInt64 {
    return FfiConverterTypeAudioOutputStream.lower(value)
}






public protocol AudioPlayerProtocol: AnyObject, Sendable {
    
    func currentTime()  -> Double
    
    func duration()  -> Double
    
    func metadata()  -> TrackMetadata
    
    func pause() 
    
    func play() throws 
    
    func seek(seconds: Double) throws 
    
    func setVolume(volume: Float) 
    
    func state()  -> PlaybackState
    
    func stop() 
    
    func volume()  -> Float
    
}
open class AudioPlayer: AudioPlayerProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_clone_audio_fn_clone_audioplayer(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_clone_audio_fn_free_audioplayer(handle, $0) }
    }

    
public static func `open`(path: String, delegate: AudioPlayerDelegate)throws  -> AudioPlayer  {
    return try  FfiConverterTypeAudioPlayer_lift(try rustCallWithError(FfiConverterTypeAudioError_lift) {
    uniffi_clone_audio_fn_constructor_audioplayer_open(
        FfiConverterString.lower(path),
        FfiConverterCallbackInterfaceAudioPlayerDelegate_lower(delegate),$0
    )
})
}
    

    
open func currentTime() -> Double  {
    return try!  FfiConverterDouble.lift(try! rustCall() {
    uniffi_clone_audio_fn_method_audioplayer_current_time(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func duration() -> Double  {
    return try!  FfiConverterDouble.lift(try! rustCall() {
    uniffi_clone_audio_fn_method_audioplayer_duration(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func metadata() -> TrackMetadata  {
    return try!  FfiConverterTypeTrackMetadata_lift(try! rustCall() {
    uniffi_clone_audio_fn_method_audioplayer_metadata(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func pause()  {try! rustCall() {
    uniffi_clone_audio_fn_method_audioplayer_pause(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func play()throws   {try rustCallWithError(FfiConverterTypeAudioError_lift) {
    uniffi_clone_audio_fn_method_audioplayer_play(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func seek(seconds: Double)throws   {try rustCallWithError(FfiConverterTypeAudioError_lift) {
    uniffi_clone_audio_fn_method_audioplayer_seek(
            self.uniffiCloneHandle(),
        FfiConverterDouble.lower(seconds),$0
    )
}
}
    
open func setVolume(volume: Float)  {try! rustCall() {
    uniffi_clone_audio_fn_method_audioplayer_set_volume(
            self.uniffiCloneHandle(),
        FfiConverterFloat.lower(volume),$0
    )
}
}
    
open func state() -> PlaybackState  {
    return try!  FfiConverterTypePlaybackState_lift(try! rustCall() {
    uniffi_clone_audio_fn_method_audioplayer_state(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func stop()  {try! rustCall() {
    uniffi_clone_audio_fn_method_audioplayer_stop(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func volume() -> Float  {
    return try!  FfiConverterFloat.lift(try! rustCall() {
    uniffi_clone_audio_fn_method_audioplayer_volume(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAudioPlayer: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = AudioPlayer

    public static func lift(_ handle: UInt64) throws -> AudioPlayer {
        return AudioPlayer(unsafeFromHandle: handle)
    }

    public static func lower(_ value: AudioPlayer) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AudioPlayer {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: AudioPlayer, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAudioPlayer_lift(_ handle: UInt64) throws -> AudioPlayer {
    return try FfiConverterTypeAudioPlayer.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAudioPlayer_lower(_ value: AudioPlayer) -> UInt64 {
    return FfiConverterTypeAudioPlayer.lower(value)
}




public struct TrackMetadata: Equatable, Hashable {
    public var title: String?
    public var artist: String?
    public var album: String?
    public var durationSeconds: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(title: String?, artist: String?, album: String?, durationSeconds: Double) {
        self.title = title
        self.artist = artist
        self.album = album
        self.durationSeconds = durationSeconds
    }

    

    
}

#if compiler(>=6)
extension TrackMetadata: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTrackMetadata: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TrackMetadata {
        return
            try TrackMetadata(
                title: FfiConverterOptionString.read(from: &buf), 
                artist: FfiConverterOptionString.read(from: &buf), 
                album: FfiConverterOptionString.read(from: &buf), 
                durationSeconds: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: TrackMetadata, into buf: inout [UInt8]) {
        FfiConverterOptionString.write(value.title, into: &buf)
        FfiConverterOptionString.write(value.artist, into: &buf)
        FfiConverterOptionString.write(value.album, into: &buf)
        FfiConverterDouble.write(value.durationSeconds, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTrackMetadata_lift(_ buf: RustBuffer) throws -> TrackMetadata {
    return try FfiConverterTypeTrackMetadata.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTrackMetadata_lower(_ value: TrackMetadata) -> RustBuffer {
    return FfiConverterTypeTrackMetadata.lower(value)
}


public enum AudioError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case FileNotFound(path: String
    )
    case UnsupportedFormat
    case DecodingFailed(reason: String
    )
    case OutputDeviceFailed(reason: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension AudioError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAudioError: FfiConverterRustBuffer {
    typealias SwiftType = AudioError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AudioError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .FileNotFound(
            path: try FfiConverterString.read(from: &buf)
            )
        case 2: return .UnsupportedFormat
        case 3: return .DecodingFailed(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 4: return .OutputDeviceFailed(
            reason: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AudioError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .FileNotFound(path):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(path, into: &buf)
            
        
        case .UnsupportedFormat:
            writeInt(&buf, Int32(2))
        
        
        case let .DecodingFailed(reason):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .OutputDeviceFailed(reason):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(reason, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAudioError_lift(_ buf: RustBuffer) throws -> AudioError {
    return try FfiConverterTypeAudioError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAudioError_lower(_ value: AudioError) -> RustBuffer {
    return FfiConverterTypeAudioError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * UniFFI-exported types for the audio engine.
 */

public enum PlaybackState: Equatable, Hashable {
    
    case idle
    case loading
    case readyToPlay
    case playing
    case paused
    case stopped
    case failed(reason: String
    )





}

#if compiler(>=6)
extension PlaybackState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePlaybackState: FfiConverterRustBuffer {
    typealias SwiftType = PlaybackState

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PlaybackState {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .idle
        
        case 2: return .loading
        
        case 3: return .readyToPlay
        
        case 4: return .playing
        
        case 5: return .paused
        
        case 6: return .stopped
        
        case 7: return .failed(reason: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PlaybackState, into buf: inout [UInt8]) {
        switch value {
        
        
        case .idle:
            writeInt(&buf, Int32(1))
        
        
        case .loading:
            writeInt(&buf, Int32(2))
        
        
        case .readyToPlay:
            writeInt(&buf, Int32(3))
        
        
        case .playing:
            writeInt(&buf, Int32(4))
        
        
        case .paused:
            writeInt(&buf, Int32(5))
        
        
        case .stopped:
            writeInt(&buf, Int32(6))
        
        
        case let .failed(reason):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(reason, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePlaybackState_lift(_ buf: RustBuffer) throws -> PlaybackState {
    return try FfiConverterTypePlaybackState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePlaybackState_lower(_ value: PlaybackState) -> RustBuffer {
    return FfiConverterTypePlaybackState.lower(value)
}





public protocol AudioPlayerDelegate: AnyObject, Sendable {
    
    func onStateChanged(state: PlaybackState) 
    
    func onTimeUpdate(currentSeconds: Double, durationSeconds: Double) 
    
    func onDidFinishPlaying() 
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceAudioPlayerDelegate {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceAudioPlayerDelegate] = [UniffiVTableCallbackInterfaceAudioPlayerDelegate(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterCallbackInterfaceAudioPlayerDelegate.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface AudioPlayerDelegate: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterCallbackInterfaceAudioPlayerDelegate.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface AudioPlayerDelegate: handle missing in uniffiClone")
            }
        },
        onStateChanged: { (
            uniffiHandle: UInt64,
            state: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceAudioPlayerDelegate.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onStateChanged(
                     state: try FfiConverterTypePlaybackState_lift(state)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onTimeUpdate: { (
            uniffiHandle: UInt64,
            currentSeconds: Double,
            durationSeconds: Double,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceAudioPlayerDelegate.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onTimeUpdate(
                     currentSeconds: try FfiConverterDouble.lift(currentSeconds),
                     durationSeconds: try FfiConverterDouble.lift(durationSeconds)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onDidFinishPlaying: { (
            uniffiHandle: UInt64,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceAudioPlayerDelegate.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onDidFinishPlaying(
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )]
}

private func uniffiCallbackInitAudioPlayerDelegate() {
    uniffi_clone_audio_fn_init_callback_vtable_audioplayerdelegate(UniffiCallbackInterfaceAudioPlayerDelegate.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceAudioPlayerDelegate {
    fileprivate static let handleMap = UniffiHandleMap<AudioPlayerDelegate>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceAudioPlayerDelegate : FfiConverter {
    typealias SwiftType = AudioPlayerDelegate
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceAudioPlayerDelegate_lift(_ handle: UInt64) throws -> AudioPlayerDelegate {
    return try FfiConverterCallbackInterfaceAudioPlayerDelegate.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceAudioPlayerDelegate_lower(_ v: AudioPlayerDelegate) -> UInt64 {
    return FfiConverterCallbackInterfaceAudioPlayerDelegate.lower(v)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceFloat: FfiConverterRustBuffer {
    typealias SwiftType = [Float]

    public static func write(_ value: [Float], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterFloat.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Float] {
        let len: Int32 = try readInt(&buf)
        var seq = [Float]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterFloat.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_clone_audio_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_clone_audio_checksum_method_audioplayer_current_time() != 37245) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_audio_checksum_method_audioplayer_duration() != 56) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_audio_checksum_method_audioplayer_metadata() != 39114) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_audio_checksum_method_audioplayer_pause() != 57407) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_audio_checksum_method_audioplayer_play() != 56614) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_audio_checksum_method_audioplayer_seek() != 21821) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_audio_checksum_method_audioplayer_set_volume() != 21395) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_audio_checksum_method_audioplayer_state() != 25830) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_audio_checksum_method_audioplayer_stop() != 36585) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_audio_checksum_method_audioplayer_volume() != 16605) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_audio_checksum_method_audiooutputstream_channels() != 34097) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_audio_checksum_method_audiooutputstream_is_playing() != 16766) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_audio_checksum_method_audiooutputstream_pause() != 9935) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_audio_checksum_method_audiooutputstream_play() != 54519) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_audio_checksum_method_audiooutputstream_sample_rate() != 7502) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_audio_checksum_method_audiooutputstream_set_volume() != 32080) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_audio_checksum_method_audiooutputstream_stop() != 1551) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_audio_checksum_method_audiooutputstream_volume() != 30141) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_audio_checksum_method_audiooutputstream_write() != 17845) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_audio_checksum_constructor_audioplayer_open() != 55669) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_audio_checksum_constructor_audiooutputstream_new() != 28795) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_audio_checksum_method_audioplayerdelegate_on_state_changed() != 41769) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_audio_checksum_method_audioplayerdelegate_on_time_update() != 64647) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_audio_checksum_method_audioplayerdelegate_on_did_finish_playing() != 40313) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitAudioPlayerDelegate()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureCloneAudioInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all