import Foundation

enum PackageGenerator {
    static func generate(
        target: String,
        sdkPath: String,
        sourceDir: String,
        stubs: Set<String>,
        sdkModules: Set<String>,
        outputDir: String,
        aquaxDir: String
    ) throws {
        let fm = FileManager.default

        // Find platform-specific files to exclude
        let sourcePath = URL(fileURLWithPath: outputDir).appendingPathComponent(sourceDir).path
        let excludes = findExcludes(in: sourcePath)

        // SDK modules that are exported as products in Clone's Package.swift.
        // AppKit is a transitive dependency of SwiftUI, not a separate product.
        // Internal modules (CloneClient, CloneProtocol, etc.) are not app dependencies.
        let exportedProducts: Set<String> = [
            "SwiftUI", "SwiftData", "Charts",
            "MediaPlayer", "AVKit", "UniformTypeIdentifiers",
            "AVFoundation", "KeychainServices",
        ]

        var sdkDeps: [String] = []
        for module in sdkModules.sorted() {
            if exportedProducts.contains(module) {
                sdkDeps.append(module)
            }
        }

        // Stub modules are also Clone products
        for stub in stubs.sorted() {
            if !sdkDeps.contains(stub) {
                sdkDeps.append(stub)
            }
        }

        // Generate SDK product dependencies
        let depsSection = sdkDeps.map { dep in
            "            .product(name: \"\(dep)\", package: \"clone\")"
        }.joined(separator: ",\n")

        // Exclude list
        let excludeList = excludes.map { "            \"\($0)\"" }.joined(separator: ",\n")
        let excludeSection = excludes.isEmpty ? "" : ",\n            exclude: [\n\(excludeList)\n            ]"

        let packageSwift = """
        // swift-tools-version: 6.0
        // Generated by ycodebuild — do not edit manually
        import PackageDescription

        let package = Package(
            name: "\(target)Aquax",
            platforms: [.macOS(.v14)],
            dependencies: [
                .package(path: "\(sdkPath)"),
            ],
            targets: [
                .executableTarget(
                    name: "\(target)",
                    dependencies: [
        \(depsSection)
                    ],
                    path: "\(sourceDir)"\(excludeSection)
                ),
            ]
        )
        """

        let packagePath = URL(fileURLWithPath: outputDir).appendingPathComponent("Package.swift").path
        try packageSwift.write(toFile: packagePath, atomically: true, encoding: .utf8)

        try fm.createDirectory(atPath: aquaxDir, withIntermediateDirectories: true)
    }

    // MARK: - Prebuilt framework mode

    static func generatePrebuilt(
        target: String,
        sdkPath: String,
        sourceDir: String,
        outputDir: String,
        aquaxDir: String
    ) throws {
        let fm = FileManager.default

        let sourcePath = URL(fileURLWithPath: outputDir).appendingPathComponent(sourceDir).path
        let excludes = findExcludes(in: sourcePath)

        // Exclude list
        let excludeList = excludes.map { "\"\($0)\"" }.joined(separator: ", ")
        let excludeSection = excludes.isEmpty ? "" : ",\n        exclude: [\(excludeList)]"

        let sdk = sdkPath
        let fw = "\(sdk)/.build/sdk/System/Library/Frameworks"
        let modules = "\(sdk)/.build/debug/Modules"
        let macroPlugin = "\(sdk)/.build/arm64-apple-macosx/debug/SwiftDataMacros-tool#SwiftDataMacros"
        let rustLib = "\(sdk)/target/debug"

        let cMapFlags = ["CText", "CAudio", "CSQLite", "CEngine"].flatMap { dir in
            ["\"-Xcc\"", "\"-fmodule-map-file=\(sdk)/Sources/\(dir)/module.modulemap\""]
        }.joined(separator: ", ")

        let fwLinkFlags = [
            "CloneProtocol", "AppKit", "UniformTypeIdentifiers", "AVKit", "KeychainServices",
            "CloneClient", "MediaPlayer", "SwiftData", "SwiftUI", "Charts", "AVFoundation",
        ].flatMap { name in
            ["\"-framework\"", "\"\(name)\""]
        }.joined(separator: ", ")

        let packageSwift = """
        // swift-tools-version: 6.0
        // Generated by ycodebuild (prebuilt mode)
        import PackageDescription

        let package = Package(
            name: "\(target)Aquax",
            platforms: [.macOS(.v14)],
            targets: [
                .executableTarget(
                    name: "\(target)",
                    path: "\(sourceDir)"\(excludeSection),
                    swiftSettings: [
                        .unsafeFlags([
                            "-F", "\(fw)",
                            "-I", "\(modules)",
                            \(cMapFlags),
                            "-load-plugin-executable", "\(macroPlugin)",
                        ]),
                    ],
                    linkerSettings: [
                        .unsafeFlags([
                            "-F", "\(fw)",
                            \(fwLinkFlags),
                            "-Xlinker", "-rpath", "-Xlinker", "\(fw)",
                            "-Xlinker", "-rpath", "-Xlinker", "\(rustLib)",
                        ]),
                    ]
                ),
            ]
        )
        """

        let packagePath = URL(fileURLWithPath: outputDir).appendingPathComponent("Package.swift").path
        try packageSwift.write(toFile: packagePath, atomically: true, encoding: .utf8)

        try fm.createDirectory(atPath: aquaxDir, withIntermediateDirectories: true)
    }

    /// Find files/directories that should be excluded (platform-specific + non-Swift resources).
    private static func findExcludes(in directory: String) -> [String] {
        let fm = FileManager.default
        guard let enumerator = fm.enumerator(
            at: URL(fileURLWithPath: directory),
            includingPropertiesForKeys: [.isDirectoryKey],
            options: [.skipsHiddenFiles]
        ) else { return [] }

        let platformSuffixes = ["+iOS", "+tvOS", "+watchOS", "+visionOS"]
        let excludedExtensions: Set<String> = [
            "plist", "xcassets", "entitlements", "xcdatamodeld",
            "storyboard", "xib", "xcodeproj", "xcworkspace",
            "svg", "png", "jpg", "jpeg", "gif", "pdf", "ico",
            "icon", "json", "strings", "stringsdict",
            "metal", "mlmodel", "intentdefinition",
        ]
        let excludedDirExtensions: Set<String> = [
            "xcassets", "xcdatamodeld", "icon", "xcodeproj", "xcworkspace",
        ]

        var excludes: [String] = []
        var excludedDirs: Set<String> = []

        for case let fileURL as URL in enumerator {
            let path = fileURL.path

            if excludedDirs.contains(where: { path.hasPrefix($0 + "/") }) {
                continue
            }

            let filename = fileURL.lastPathComponent
            let ext = fileURL.pathExtension.lowercased()
            let rel = path.replacingOccurrences(of: directory + "/", with: "")

            let isDir = (try? fileURL.resourceValues(forKeys: [.isDirectoryKey]))?.isDirectory ?? false
            if isDir && excludedDirExtensions.contains(ext) {
                excludes.append(rel)
                excludedDirs.insert(path)
                continue
            }

            if platformSuffixes.contains(where: { filename.contains($0) }) {
                excludes.append(rel)
                continue
            }

            // Exclude test files — they belong in test targets, not the app
            if !isDir && filename.hasSuffix("Tests.swift") {
                excludes.append(rel)
                continue
            }

            if !isDir && excludedExtensions.contains(ext) {
                excludes.append(rel)
            }
        }

        return excludes.sorted()
    }
}
