import Foundation

enum PackageGenerator {
    static func generate(
        target: String,
        sdkPath: String,
        sourceDir: String,
        stubs: Set<String>,
        sdkModules: Set<String>,
        outputDir: String,
        aquaxDir: String
    ) throws {
        let fm = FileManager.default

        // Find platform-specific files to exclude
        let sourcePath = URL(fileURLWithPath: outputDir).appendingPathComponent(sourceDir).path
        let excludes = findExcludes(in: sourcePath)

        // SDK products exposed by Clone's Package.swift.
        // AppKit is a transitive dependency of SwiftUI, not a separate product.
        var sdkDeps: [String] = []
        if sdkModules.contains("SwiftUI") {
            sdkDeps.append("SwiftUI")
        }
        if sdkModules.contains("SwiftData") {
            sdkDeps.append("SwiftData")
        }

        // Stubs that need SwiftUI as a dependency
        let stubsNeedingSwiftUI: Set<String> = ["Charts"]

        let sortedStubs = stubs.sorted()

        // Generate stub target entries
        let stubTargets = sortedStubs.map { stub in
            if stubsNeedingSwiftUI.contains(stub) {
                return "        .target(name: \"\(stub)\", dependencies: [.product(name: \"SwiftUI\", package: \"clone\")], path: \".aquax/stubs/\(stub)\")"
            }
            return "        .target(name: \"\(stub)\", path: \".aquax/stubs/\(stub)\")"
        }.joined(separator: ",\n")

        // SDK product dependencies
        let sdkProductDeps = sdkDeps.map { dep in
            "            .product(name: \"\(dep)\", package: \"clone\")"
        }.joined(separator: ",\n")

        // Stub dependency refs
        let stubDeps = sortedStubs.map { "            \"\($0)\"" }.joined(separator: ",\n")

        // Exclude list
        let excludeList = excludes.map { "            \"\($0)\"" }.joined(separator: ",\n")
        let excludeSection = excludes.isEmpty ? "" : ",\n            exclude: [\n\(excludeList)\n            ]"

        // All deps
        var allDeps = [String]()
        if !sdkProductDeps.isEmpty { allDeps.append(sdkProductDeps) }
        if !stubDeps.isEmpty { allDeps.append(stubDeps) }
        let depsSection = allDeps.joined(separator: ",\n")

        let packageSwift = """
        // swift-tools-version: 6.0
        // Generated by ycodebuild — do not edit manually
        import PackageDescription

        let package = Package(
            name: "\(target)Aquax",
            platforms: [.macOS(.v14)],
            dependencies: [
                .package(path: "\(sdkPath)"),
            ],
            targets: [
        \(stubTargets),

                .executableTarget(
                    name: "\(target)",
                    dependencies: [
        \(depsSection)
                    ],
                    path: "\(sourceDir)"\(excludeSection)
                ),
            ]
        )
        """

        let packagePath = URL(fileURLWithPath: outputDir).appendingPathComponent("Package.swift").path
        try packageSwift.write(toFile: packagePath, atomically: true, encoding: .utf8)

        try fm.createDirectory(atPath: aquaxDir, withIntermediateDirectories: true)
    }

    /// Find files/directories that should be excluded (platform-specific + non-Swift resources).
    private static func findExcludes(in directory: String) -> [String] {
        let fm = FileManager.default
        guard let enumerator = fm.enumerator(
            at: URL(fileURLWithPath: directory),
            includingPropertiesForKeys: [.isDirectoryKey],
            options: [.skipsHiddenFiles]
        ) else { return [] }

        let platformSuffixes = ["+iOS", "+tvOS", "+watchOS", "+visionOS"]
        let excludedExtensions: Set<String> = [
            "plist", "xcassets", "entitlements", "xcdatamodeld",
            "storyboard", "xib", "xcodeproj", "xcworkspace",
            "svg", "png", "jpg", "jpeg", "gif", "pdf", "ico",
            "icon", "json", "strings", "stringsdict",
            "metal", "mlmodel", "intentdefinition",
        ]
        let excludedDirExtensions: Set<String> = [
            "xcassets", "xcdatamodeld", "icon", "xcodeproj", "xcworkspace",
        ]

        var excludes: [String] = []
        var excludedDirs: Set<String> = []

        for case let fileURL as URL in enumerator {
            let path = fileURL.path

            if excludedDirs.contains(where: { path.hasPrefix($0 + "/") }) {
                continue
            }

            let filename = fileURL.lastPathComponent
            let ext = fileURL.pathExtension.lowercased()
            let rel = path.replacingOccurrences(of: directory + "/", with: "")

            let isDir = (try? fileURL.resourceValues(forKeys: [.isDirectoryKey]))?.isDirectory ?? false
            if isDir && excludedDirExtensions.contains(ext) {
                excludes.append(rel)
                excludedDirs.insert(path)
                continue
            }

            if platformSuffixes.contains(where: { filename.contains($0) }) {
                excludes.append(rel)
                continue
            }

            if !isDir && excludedExtensions.contains(ext) {
                excludes.append(rel)
            }
        }

        return excludes.sorted()
    }
}
