import Foundation

enum PackageGenerator {
    static func generate(
        target: String,
        sdkPath: String,
        sourceDir: String,
        stubs: Set<String>,
        sdkModules: Set<String>,
        outputDir: String,
        aquaxDir: String
    ) throws {
        let fm = FileManager.default

        // Find platform-specific files to exclude
        let sourcePath = URL(fileURLWithPath: outputDir).appendingPathComponent(sourceDir).path
        let excludes = findExcludes(in: sourcePath)

        // Build SDK dependencies (only SwiftUI and SwiftData are products)
        var sdkDeps: [String] = []
        if sdkModules.contains("SwiftUI") {
            sdkDeps.append("SwiftUI")
        }
        if sdkModules.contains("SwiftData") {
            sdkDeps.append("SwiftData")
        }
        if sdkModules.contains("AppKit") && !sdkModules.contains("SwiftUI") {
            // AppKit is a transitive dependency of SwiftUI, but add explicitly if needed alone
            sdkDeps.append("AppKit")
        }

        let sortedStubs = stubs.sorted()

        // Generate stub target entries
        let stubTargets = sortedStubs.map { stub in
            "        .target(name: \"\(stub)\", path: \".aquax/stubs/\(stub)\")"
        }.joined(separator: ",\n")

        // Generate stub dependency references for the app target
        let stubDeps = sortedStubs.map { "            \"\($0)\"" }.joined(separator: ",\n")

        // Generate SDK product dependencies
        let sdkProductDeps = sdkDeps.map { dep in
            "            .product(name: \"\(dep)\", package: \"clone\")"
        }.joined(separator: ",\n")

        // Generate exclude list
        let excludeList = excludes.map { "            \"\($0)\"" }.joined(separator: ",\n")
        let excludeSection = excludes.isEmpty ? "" : ",\n            exclude: [\n\(excludeList)\n            ]"

        // All dependencies for the app target
        var allDeps = [String]()
        if !sdkProductDeps.isEmpty { allDeps.append(sdkProductDeps) }
        if !stubDeps.isEmpty { allDeps.append(stubDeps) }
        let depsSection = allDeps.joined(separator: ",\n")

        let packageSwift = """
        // swift-tools-version: 5.9
        // Generated by ycodebuild — do not edit manually
        import PackageDescription

        let package = Package(
            name: "\(target)Aquax",
            platforms: [.macOS(.v14)],
            dependencies: [
                .package(path: "\(sdkPath)"),
            ],
            targets: [
                // Stub modules for unavailable frameworks
        \(stubTargets),

                .executableTarget(
                    name: "\(target)",
                    dependencies: [
        \(depsSection)
                    ],
                    path: "\(sourceDir)"\(excludeSection)
                ),
            ]
        )
        """

        // Write Package.swift to the parent directory (not inside .aquax)
        let packagePath = URL(fileURLWithPath: outputDir).appendingPathComponent("Package.swift").path
        try packageSwift.write(toFile: packagePath, atomically: true, encoding: .utf8)

        // Also ensure .aquax dir exists
        try fm.createDirectory(atPath: aquaxDir, withIntermediateDirectories: true)
    }

    /// Find files that should be excluded (platform-specific).
    private static func findExcludes(in directory: String) -> [String] {
        let fm = FileManager.default
        guard let enumerator = fm.enumerator(
            at: URL(fileURLWithPath: directory),
            includingPropertiesForKeys: nil,
            options: [.skipsHiddenFiles]
        ) else { return [] }

        var excludes: [String] = []
        let platformSuffixes = ["+iOS", "+tvOS", "+watchOS", "+visionOS"]

        for case let fileURL as URL in enumerator {
            let filename = fileURL.lastPathComponent
            if platformSuffixes.contains(where: { filename.contains($0) }) {
                // Get relative path from directory
                let rel = fileURL.path.replacingOccurrences(of: directory + "/", with: "")
                excludes.append(rel)
            }
        }

        return excludes.sorted()
    }
}
