import Foundation

enum StubGenerator {
    static func generate(modules: Set<String>, outputDir: String) throws {
        let fm = FileManager.default

        for module in modules.sorted() {
            let moduleDir = URL(fileURLWithPath: outputDir).appendingPathComponent(module)
            try fm.createDirectory(at: moduleDir, withIntermediateDirectories: true)

            let stubContent = stubSource(for: module)
            let filePath = moduleDir.appendingPathComponent("\(module).swift")
            try stubContent.write(to: filePath, atomically: true, encoding: .utf8)
        }
    }

    private static func stubSource(for module: String) -> String {
        switch module {
        case "Combine":
            return combineStub
        case "AVFoundation":
            return avFoundationStub
        case "MediaPlayer":
            return mediaPlayerStub
        case "Charts":
            return chartsStub
        case "CoreData":
            return coreDataStub
        case "AuthenticationServices":
            return authenticationServicesStub
        case "LocalAuthentication":
            return localAuthenticationStub
        case "StoreKit":
            return storeKitStub
        case "MusicKit":
            return musicKitStub
        case "UserNotifications":
            return userNotificationsStub
        case "CoreImage":
            return coreImageStub
        case "WidgetKit":
            return widgetKitStub
        default:
            return minimalStub(module: module)
        }
    }

    private static func minimalStub(module: String) -> String {
        """
        // Stub module: \(module)
        // Generated by ycodebuild — provides empty declarations so code compiles.
        """
    }

    // MARK: - Combine

    private static let combineStub = """
    // Stub module: Combine
    // Generated by ycodebuild — minimal Combine types for compilation.
    // Cannot import Foundation (circular dependency), so types are self-contained.

    public protocol Publisher {
        associatedtype Output
        associatedtype Failure: Error
    }

    public protocol Subscriber {
        associatedtype Input
        associatedtype Failure: Error
    }

    public protocol Subscription {
        func request(_ demand: Subscribers.Demand)
        func cancel()
    }

    public enum Subscribers {
        public struct Demand: Equatable, Comparable {
            public static let unlimited = Demand()
            public static let none = Demand()
            public static func max(_ value: Int) -> Demand { Demand() }
            public static func < (lhs: Demand, rhs: Demand) -> Bool { false }
        }
        public struct Completion<Failure: Error> {
            public static var finished: Completion { Completion() }
        }
    }

    open class PassthroughSubject<Output, Failure: Error>: Publisher {
        public init() {}
        public func send(_ value: Output) {}
        public func send(completion: Subscribers.Completion<Failure>) {}
    }

    open class CurrentValueSubject<Output, Failure: Error>: Publisher {
        public var value: Output
        public init(_ value: Output) { self.value = value }
        public func send(_ value: Output) { self.value = value }
    }

    public final class AnyCancellable: Hashable {
        private let cancelAction: () -> Void
        public init(_ cancel: @escaping () -> Void) { self.cancelAction = cancel }
        public func cancel() { cancelAction() }
        public func store(in set: inout Set<AnyCancellable>) { set.insert(self) }
        public static func == (lhs: AnyCancellable, rhs: AnyCancellable) -> Bool {
            lhs === rhs
        }
        public func hash(into hasher: inout Hasher) {
            hasher.combine(ObjectIdentifier(self))
        }
    }

    public typealias Cancellable = AnyCancellable

    public protocol ObservableObject: AnyObject {
        associatedtype ObjectWillChangePublisher: Publisher = ObservableObjectPublisher
        var objectWillChange: ObjectWillChangePublisher { get }
    }

    public class ObservableObjectPublisher: Publisher {
        public typealias Output = Void
        public typealias Failure = Never
        public init() {}
        public func send() {}
    }

    extension ObservableObject where ObjectWillChangePublisher == ObservableObjectPublisher {
        public var objectWillChange: ObservableObjectPublisher { ObservableObjectPublisher() }
    }

    @propertyWrapper
    public struct Published<Value> {
        public var wrappedValue: Value
        public var projectedValue: Publisher {
            Publisher()
        }
        public init(wrappedValue: Value) { self.wrappedValue = wrappedValue }
        public init(initialValue: Value) { self.wrappedValue = initialValue }
        public struct Publisher: Combine.Publisher {
            public typealias Output = Value
            public typealias Failure = Never
        }
    }

    public struct AnyPublisher<Output, Failure: Error>: Publisher {}

    public struct Just<Output>: Publisher {
        public typealias Failure = Never
        public let output: Output
        public init(_ output: Output) { self.output = output }
    }

    public struct Empty<Output, Failure: Error>: Publisher {
        public init() {}
        public init(completeImmediately: Bool = true) {}
    }

    extension Publisher {
        public func sink(receiveCompletion: @escaping (Subscribers.Completion<Failure>) -> Void,
                         receiveValue: @escaping (Output) -> Void) -> AnyCancellable {
            AnyCancellable {}
        }

        public func map<T>(_ transform: @escaping (Output) -> T) -> AnyPublisher<T, Failure> {
            AnyPublisher<T, Failure>()
        }

        public func compactMap<T>(_ transform: @escaping (Output) -> T?) -> AnyPublisher<T, Failure> {
            AnyPublisher<T, Failure>()
        }

        public func filter(_ isIncluded: @escaping (Output) -> Bool) -> AnyPublisher<Output, Failure> {
            AnyPublisher<Output, Failure>()
        }

        public func eraseToAnyPublisher() -> AnyPublisher<Output, Failure> {
            AnyPublisher<Output, Failure>()
        }

        public func removeDuplicates() -> AnyPublisher<Output, Failure> {
            AnyPublisher<Output, Failure>()
        }

        public func combineLatest<P: Publisher>(_ other: P) -> AnyPublisher<(Output, P.Output), Failure> where P.Failure == Failure {
            AnyPublisher<(Output, P.Output), Failure>()
        }
    }

    extension Publisher where Failure == Never {
        public func sink(receiveValue: @escaping (Output) -> Void) -> AnyCancellable {
            AnyCancellable {}
        }

        public func assign<Root>(to keyPath: ReferenceWritableKeyPath<Root, Output>, on object: Root) -> AnyCancellable {
            AnyCancellable {}
        }
    }
    """

    // MARK: - AVFoundation

    private static let avFoundationStub = """
    // Stub module: AVFoundation
    // Generated by ycodebuild — no-op audio/video types for compilation.
    import Foundation

    public class AVPlayer {
        public var rate: Float = 0
        public var currentItem: AVPlayerItem?

        public init() {}
        public init(url: URL) {}
        public init(playerItem item: AVPlayerItem?) { self.currentItem = item }

        public func play() {}
        public func pause() {}
        public func seek(to time: CMTime) {}
        public func seek(to time: CMTime, completionHandler: @escaping (Bool) -> Void) { completionHandler(true) }
        public func replaceCurrentItem(with item: AVPlayerItem?) { currentItem = item }

        public func addPeriodicTimeObserver(forInterval interval: CMTime, queue: DispatchQueue?, using block: @escaping (CMTime) -> Void) -> Any {
            0 as Int
        }
        public func removeTimeObserver(_ observer: Any) {}
    }

    public class AVPlayerItem {
        public var duration: CMTime { .zero }
        public var status: Status = .unknown

        public enum Status: Int { case unknown, readyToPlay, failed }

        public init(url: URL) {}
    }

    public class AVAsset {
        public var duration: CMTime { .zero }
        public init(url: URL) {}
    }

    public class AVAudioSession {
        public static let sharedInstance = AVAudioSession()

        public enum Category: String { case playback, ambient, soloAmbient, record, playAndRecord, multiRoute }
        public enum Mode: String { case `default`, voiceChat, videoChat, gameChat, measurement, moviePlayback, spokenAudio }
        public struct CategoryOptions: OptionSet {
            public let rawValue: UInt
            public init(rawValue: UInt) { self.rawValue = rawValue }
            public static let mixWithOthers = CategoryOptions(rawValue: 1)
            public static let duckOthers = CategoryOptions(rawValue: 2)
            public static let allowBluetooth = CategoryOptions(rawValue: 4)
        }

        public func setCategory(_ category: Category, mode: Mode = .default, options: CategoryOptions = []) throws {}
        public func setActive(_ active: Bool) throws {}
        public func setActive(_ active: Bool, options: SetActiveOptions = []) throws {}

        public struct SetActiveOptions: OptionSet {
            public let rawValue: UInt
            public init(rawValue: UInt) { self.rawValue = rawValue }
            public static let notifyOthersOnDeactivation = SetActiveOptions(rawValue: 1)
        }
    }

    public struct CMTime: Equatable {
        public var seconds: Double
        public var value: Int64
        public var timescale: Int32

        public static let zero = CMTime(seconds: 0, value: 0, timescale: 1)

        public init(seconds: Double, preferredTimescale: Int32 = 600) {
            self.seconds = seconds
            self.value = Int64(seconds * Double(preferredTimescale))
            self.timescale = preferredTimescale
        }

        private init(seconds: Double, value: Int64, timescale: Int32) {
            self.seconds = seconds
            self.value = value
            self.timescale = timescale
        }
    }

    public func CMTimeGetSeconds(_ time: CMTime) -> Double { time.seconds }
    public func CMTimeMake(value: Int64, timescale: Int32) -> CMTime {
        CMTime(seconds: Double(value) / Double(timescale), preferredTimescale: timescale)
    }
    """

    // MARK: - MediaPlayer

    private static let mediaPlayerStub = """
    // Stub module: MediaPlayer
    // Generated by ycodebuild — no-op now playing and remote command types.
    import Foundation

    public class MPNowPlayingInfoCenter {
        public static let `default` = MPNowPlayingInfoCenter()
        public var nowPlayingInfo: [String: Any]?
        public var playbackState: MPNowPlayingPlaybackState = .unknown
    }

    public enum MPNowPlayingPlaybackState: UInt {
        case unknown, playing, paused, stopped, interrupted
    }

    public class MPRemoteCommandCenter {
        public static func shared() -> MPRemoteCommandCenter { _shared }
        private static let _shared = MPRemoteCommandCenter()

        public let playCommand = MPRemoteCommand()
        public let pauseCommand = MPRemoteCommand()
        public let togglePlayPauseCommand = MPRemoteCommand()
        public let nextTrackCommand = MPRemoteCommand()
        public let previousTrackCommand = MPRemoteCommand()
        public let changePlaybackPositionCommand = MPRemoteCommand()
        public let skipForwardCommand = MPSkipIntervalCommand()
        public let skipBackwardCommand = MPSkipIntervalCommand()
        public let likeCommand = MPFeedbackCommand()
        public let dislikeCommand = MPFeedbackCommand()
    }

    public class MPRemoteCommand {
        public var isEnabled: Bool = true
        @discardableResult
        public func addTarget(handler: @escaping (MPRemoteCommandEvent) -> MPRemoteCommandHandlerStatus) -> Any {
            NSObject()
        }
        public func removeTarget(_ target: Any?) {}
    }

    public class MPSkipIntervalCommand: MPRemoteCommand {
        public var preferredIntervals: [NSNumber] = []
    }

    public class MPFeedbackCommand: MPRemoteCommand {
        public var isActive: Bool = false
    }

    public class MPRemoteCommandEvent {
        public var timestamp: TimeInterval { 0 }
    }

    public class MPChangePlaybackPositionCommandEvent: MPRemoteCommandEvent {
        public var positionTime: TimeInterval { 0 }
    }

    public class MPSkipIntervalCommandEvent: MPRemoteCommandEvent {
        public var interval: TimeInterval { 0 }
    }

    public enum MPRemoteCommandHandlerStatus: Int {
        case success, noSuchContent, noActionableNowPlayingItem, deviceNotFound, commandFailed
    }

    // Now playing info property keys
    public let MPMediaItemPropertyTitle = "title"
    public let MPMediaItemPropertyArtist = "artist"
    public let MPMediaItemPropertyAlbumTitle = "albumTitle"
    public let MPMediaItemPropertyPlaybackDuration = "playbackDuration"
    public let MPNowPlayingInfoPropertyElapsedPlaybackTime = "elapsedPlaybackTime"
    public let MPNowPlayingInfoPropertyPlaybackRate = "playbackRate"
    public let MPMediaItemPropertyArtwork = "artwork"

    public class MPMediaItemArtwork {
        public init(boundsSize: CGSize, requestHandler: @escaping (CGSize) -> Any) {}
    }
    """

    // MARK: - Charts

    private static let chartsStub = """
    // Stub module: Charts
    // Generated by ycodebuild — empty chart views for compilation.
    import SwiftUI

    public struct Chart<Content>: View {
        public init(@ChartContentBuilder content: () -> Content) {}
        public var body: some View { EmptyView() }
    }

    @resultBuilder
    public struct ChartContentBuilder {
        public static func buildBlock<C>(_ content: C) -> C { content }
        public static func buildBlock() -> EmptyChartContent { EmptyChartContent() }
        public static func buildOptional<C>(_ content: C?) -> C? { content }
        public static func buildEither<T, F>(first content: T) -> ChartEither<T, F> { .first(content) }
        public static func buildEither<T, F>(second content: F) -> ChartEither<T, F> { .second(content) }
    }

    public struct EmptyChartContent {}
    public enum ChartEither<T, F> { case first(T), second(F) }

    public struct BarMark {
        public init(x: PlottableValue<String>? = nil, y: PlottableValue<Double>? = nil) {}
        public init(x: PlottableValue<Double>? = nil, y: PlottableValue<String>? = nil) {}
        public func foregroundStyle(by value: PlottableValue<String>) -> BarMark { self }
    }

    public struct LineMark {
        public init(x: PlottableValue<String>? = nil, y: PlottableValue<Double>? = nil) {}
        public init(x: PlottableValue<Double>? = nil, y: PlottableValue<Double>? = nil) {}
    }

    public struct AreaMark {
        public init(x: PlottableValue<String>? = nil, y: PlottableValue<Double>? = nil) {}
    }

    public struct PointMark {
        public init(x: PlottableValue<String>? = nil, y: PlottableValue<Double>? = nil) {}
    }

    public struct RuleMark {
        public init(y: PlottableValue<Double>? = nil) {}
        public init(x: PlottableValue<Double>? = nil) {}
    }

    public struct PlottableValue<T> {
        public static func value(_ label: String, _ value: T) -> PlottableValue { PlottableValue() }
    }
    """

    // MARK: - CoreData

    private static let coreDataStub = """
    // Stub module: CoreData
    // Generated by ycodebuild — minimal CoreData types for migration period.
    import Foundation

    open class NSManagedObject: NSObject {
        public override init() { super.init() }
    }

    open class NSManagedObjectContext: NSObject {
        public enum ConcurrencyType: UInt { case mainQueueConcurrencyType, privateQueueConcurrencyType }
        public init(concurrencyType ct: ConcurrencyType) { super.init() }
        public func fetch<T>(_ request: NSFetchRequest<T>) throws -> [T] { [] }
        public func save() throws {}
        public func delete(_ object: NSManagedObject) {}
    }

    open class NSFetchRequest<ResultType>: NSObject {
        public var predicate: NSPredicate?
        public var sortDescriptors: [NSSortDescriptor]?
        public var fetchLimit: Int = 0
        public override init() { super.init() }
        public init(entityName: String) { super.init() }
    }

    open class NSPersistentContainer: NSObject {
        public let name: String
        public var viewContext: NSManagedObjectContext { NSManagedObjectContext(concurrencyType: .mainQueueConcurrencyType) }
        public init(name: String) { self.name = name; super.init() }
        public func loadPersistentStores(completionHandler: @escaping (Any, Error?) -> Void) {
            completionHandler(NSObject(), nil)
        }
    }

    open class NSEntityDescription: NSObject {}
    open class NSFetchedResultsController<ResultType: NSFetchRequestResult>: NSObject {}
    public protocol NSFetchRequestResult: NSObjectProtocol {}
    extension NSManagedObject: NSFetchRequestResult {}
    """

    // MARK: - AuthenticationServices

    private static let authenticationServicesStub = """
    // Stub module: AuthenticationServices
    // Generated by ycodebuild — no-op auth types.
    import Foundation

    public class ASAuthorizationController {
        public init(authorizationRequests: [ASAuthorizationRequest]) {}
        public var delegate: ASAuthorizationControllerDelegate?
        public func performRequests() {}
    }

    public protocol ASAuthorizationControllerDelegate: AnyObject {
        func authorizationController(controller: ASAuthorizationController, didCompleteWithAuthorization authorization: ASAuthorization)
        func authorizationController(controller: ASAuthorizationController, didCompleteWithError error: Error)
    }

    public class ASAuthorization {
        public var credential: ASAuthorizationCredential { fatalError("stub") }
    }

    public protocol ASAuthorizationCredential: NSObjectProtocol {}
    public class ASAuthorizationRequest: NSObject {}

    public class ASAuthorizationAppleIDProvider: NSObject {
        public func createRequest() -> ASAuthorizationAppleIDRequest { ASAuthorizationAppleIDRequest() }
    }

    public class ASAuthorizationAppleIDRequest: ASAuthorizationRequest {
        public var requestedScopes: [ASAuthorization.Scope]?
    }

    extension ASAuthorization {
        public struct Scope: RawRepresentable, Hashable {
            public let rawValue: String
            public init(rawValue: String) { self.rawValue = rawValue }
            public static let fullName = Scope(rawValue: "fullName")
            public static let email = Scope(rawValue: "email")
        }
    }

    public class ASAuthorizationAppleIDCredential: NSObject, ASAuthorizationCredential {
        public var user: String { "" }
        public var identityToken: Data? { nil }
        public var authorizationCode: Data? { nil }
    }
    """

    // MARK: - LocalAuthentication

    private static let localAuthenticationStub = """
    // Stub module: LocalAuthentication
    // Generated by ycodebuild — no-op biometric types.
    import Foundation

    public class LAContext {
        public init() {}
        public var localizedFallbackTitle: String?
        public var localizedCancelTitle: String?

        public enum BiometryType: Int { case none, touchID, faceID, opticID }
        public var biometryType: BiometryType { .none }

        public func canEvaluatePolicy(_ policy: LAPolicy, error: NSErrorPointer) -> Bool { false }
        public func evaluatePolicy(_ policy: LAPolicy, localizedReason: String, reply: @escaping (Bool, Error?) -> Void) {
            reply(false, nil)
        }
    }

    public enum LAPolicy: Int {
        case deviceOwnerAuthenticationWithBiometrics = 1
        case deviceOwnerAuthentication = 2
    }
    """

    // MARK: - StoreKit

    private static let storeKitStub = """
    // Stub module: StoreKit
    // Generated by ycodebuild — no-op in-app purchase types.
    import Foundation

    public struct Product: Identifiable {
        public var id: String { "" }
        public var displayName: String { "" }
        public var displayPrice: String { "" }
        public var description: String { "" }

        public enum ProductType { case consumable, nonConsumable, autoRenewable, nonRenewable }
        public var type: ProductType { .nonConsumable }

        public static func products(for identifiers: some Collection<String>) async throws -> [Product] { [] }
        public func purchase() async throws -> PurchaseResult { .userCancelled }
    }

    public enum PurchaseResult {
        case success(VerificationResult<Transaction>)
        case userCancelled
        case pending
    }

    public enum VerificationResult<T> {
        case verified(T)
        case unverified(T, Error)
    }

    public struct Transaction: Identifiable {
        public var id: UInt64 { 0 }
        public var productID: String { "" }
        public func finish() async {}
        public static var updates: AsyncStream<VerificationResult<Transaction>> {
            AsyncStream { $0.finish() }
        }
    }
    """

    // MARK: - MusicKit

    private static let musicKitStub = """
    // Stub module: MusicKit
    // Generated by ycodebuild — no-op music types.
    import Foundation

    public enum MusicAuthorization {
        public enum Status { case authorized, denied, notDetermined, restricted }
        public static func request() async -> Status { .denied }
        public static var currentStatus: Status { .notDetermined }
    }
    """

    // MARK: - UserNotifications

    private static let userNotificationsStub = """
    // Stub module: UserNotifications
    // Generated by ycodebuild — no-op notification types.
    import Foundation

    public class UNUserNotificationCenter {
        public static func current() -> UNUserNotificationCenter { _shared }
        private static let _shared = UNUserNotificationCenter()

        public func requestAuthorization(options: UNAuthorizationOptions = [], completionHandler: @escaping (Bool, Error?) -> Void) {
            completionHandler(false, nil)
        }
        public func add(_ request: UNNotificationRequest, withCompletionHandler: ((Error?) -> Void)? = nil) {}
    }

    public struct UNAuthorizationOptions: OptionSet {
        public let rawValue: UInt
        public init(rawValue: UInt) { self.rawValue = rawValue }
        public static let alert = UNAuthorizationOptions(rawValue: 1)
        public static let sound = UNAuthorizationOptions(rawValue: 2)
        public static let badge = UNAuthorizationOptions(rawValue: 4)
    }

    public class UNNotificationRequest {
        public static func request(identifier: String, content: UNMutableNotificationContent, trigger: UNNotificationTrigger?) -> UNNotificationRequest { UNNotificationRequest() }
    }

    public class UNMutableNotificationContent {
        public var title: String = ""
        public var body: String = ""
        public var sound: UNNotificationSound?
    }

    public class UNNotificationSound {
        public static let `default` = UNNotificationSound()
    }

    public class UNNotificationTrigger {}
    """

    // MARK: - CoreImage

    private static let coreImageStub = """
    // Stub module: CoreImage
    // Generated by ycodebuild — no-op image processing types.
    import Foundation

    public class CIImage {
        public init() {}
        public init?(contentsOf url: URL) {}
        public var extent: CGRect { .zero }
    }

    public class CIContext {
        public init() {}
    }

    public class CIFilter {
        public var outputImage: CIImage? { nil }
        public init?(name: String) {}
        public func setValue(_ value: Any?, forKey key: String) {}
    }
    """

    // MARK: - WidgetKit

    private static let widgetKitStub = """
    // Stub module: WidgetKit
    // Generated by ycodebuild — no-op widget types.
    import Foundation

    public protocol Widget {
        associatedtype Body
        var body: Body { get }
    }

    public struct WidgetCenter {
        public static let shared = WidgetCenter()
        public func reloadAllTimelines() {}
        public func reloadTimelines(ofKind kind: String) {}
    }
    """
}
