// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(clone_engineFFI)
import clone_engineFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_clone_render_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_clone_render_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureCloneRenderInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * UniFFI-exported headless renderer for app-side rendering.
 * Thread-safe wrapper around HeadlessDevice (macOS: IOSurface, Linux: stub).
 */
public protocol AppRendererProtocol: AnyObject, Sendable {
    
    /**
     * Get the current surface ID. Returns 0 if no render has happened yet.
     */
    func iosurfaceId()  -> UInt32
    
    /**
     * Create a Mach port send right for the current front surface.
     */
    func machPort()  -> UInt32
    
    /**
     * Create a Mach port for the surface at the given buffer index (0 or 1).
     */
    func machPortAt(index: UInt32)  -> UInt32
    
    /**
     * Render commands into a shared texture.
     * Returns the surface ID for cross-process sharing (IOSurface ID on macOS).
     */
    func render(commands: [RenderCommand], width: UInt32, height: UInt32, scale: Float, transparent: Bool) throws  -> UInt32
    
    /**
     * Render commands to BGRA8 pixel data (readback, slow).
     */
    func renderToPixels(commands: [RenderCommand], width: UInt32, height: UInt32, scale: Float) throws  -> Data
    
    /**
     * Render commands to BGRA8 pixel data with transparent background.
     */
    func renderToPixelsTransparent(commands: [RenderCommand], width: UInt32, height: UInt32, scale: Float) throws  -> Data
    
    /**
     * True if textures were reallocated since the last call.
     * Resets the flag after reading.
     */
    func takeTexturesChanged()  -> Bool
    
}
/**
 * UniFFI-exported headless renderer for app-side rendering.
 * Thread-safe wrapper around HeadlessDevice (macOS: IOSurface, Linux: stub).
 */
open class AppRenderer: AppRendererProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_clone_render_fn_clone_apprenderer(self.handle, $0) }
    }
    /**
     * Create a new headless GPU renderer.
     */
public convenience init()throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeRenderError_lift) {
    uniffi_clone_render_fn_constructor_apprenderer_new($0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_clone_render_fn_free_apprenderer(handle, $0) }
    }

    

    
    /**
     * Get the current surface ID. Returns 0 if no render has happened yet.
     */
open func iosurfaceId() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_clone_render_fn_method_apprenderer_iosurface_id(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Create a Mach port send right for the current front surface.
     */
open func machPort() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_clone_render_fn_method_apprenderer_mach_port(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Create a Mach port for the surface at the given buffer index (0 or 1).
     */
open func machPortAt(index: UInt32) -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_clone_render_fn_method_apprenderer_mach_port_at(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(index),$0
    )
})
}
    
    /**
     * Render commands into a shared texture.
     * Returns the surface ID for cross-process sharing (IOSurface ID on macOS).
     */
open func render(commands: [RenderCommand], width: UInt32, height: UInt32, scale: Float, transparent: Bool)throws  -> UInt32  {
    return try  FfiConverterUInt32.lift(try rustCallWithError(FfiConverterTypeRenderError_lift) {
    uniffi_clone_render_fn_method_apprenderer_render(
            self.uniffiCloneHandle(),
        FfiConverterSequenceTypeRenderCommand.lower(commands),
        FfiConverterUInt32.lower(width),
        FfiConverterUInt32.lower(height),
        FfiConverterFloat.lower(scale),
        FfiConverterBool.lower(transparent),$0
    )
})
}
    
    /**
     * Render commands to BGRA8 pixel data (readback, slow).
     */
open func renderToPixels(commands: [RenderCommand], width: UInt32, height: UInt32, scale: Float)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeRenderError_lift) {
    uniffi_clone_render_fn_method_apprenderer_render_to_pixels(
            self.uniffiCloneHandle(),
        FfiConverterSequenceTypeRenderCommand.lower(commands),
        FfiConverterUInt32.lower(width),
        FfiConverterUInt32.lower(height),
        FfiConverterFloat.lower(scale),$0
    )
})
}
    
    /**
     * Render commands to BGRA8 pixel data with transparent background.
     */
open func renderToPixelsTransparent(commands: [RenderCommand], width: UInt32, height: UInt32, scale: Float)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeRenderError_lift) {
    uniffi_clone_render_fn_method_apprenderer_render_to_pixels_transparent(
            self.uniffiCloneHandle(),
        FfiConverterSequenceTypeRenderCommand.lower(commands),
        FfiConverterUInt32.lower(width),
        FfiConverterUInt32.lower(height),
        FfiConverterFloat.lower(scale),$0
    )
})
}
    
    /**
     * True if textures were reallocated since the last call.
     * Resets the flag after reading.
     */
open func takeTexturesChanged() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_clone_render_fn_method_apprenderer_take_textures_changed(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAppRenderer: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = AppRenderer

    public static func lift(_ handle: UInt64) throws -> AppRenderer {
        return AppRenderer(unsafeFromHandle: handle)
    }

    public static func lower(_ value: AppRenderer) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AppRenderer {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: AppRenderer, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAppRenderer_lift(_ handle: UInt64) throws -> AppRenderer {
    return try FfiConverterTypeAppRenderer.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAppRenderer_lower(_ value: AppRenderer) -> UInt64 {
    return FfiConverterTypeAppRenderer.lower(value)
}




/**
 * Decoded image result.
 */
public struct DecodedImage: Equatable, Hashable {
    public var width: UInt32
    public var height: UInt32
    public var rgbaData: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(width: UInt32, height: UInt32, rgbaData: Data) {
        self.width = width
        self.height = height
        self.rgbaData = rgbaData
    }

    

    
}

#if compiler(>=6)
extension DecodedImage: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDecodedImage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DecodedImage {
        return
            try DecodedImage(
                width: FfiConverterUInt32.read(from: &buf), 
                height: FfiConverterUInt32.read(from: &buf), 
                rgbaData: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: DecodedImage, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.width, into: &buf)
        FfiConverterUInt32.write(value.height, into: &buf)
        FfiConverterData.write(value.rgbaData, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDecodedImage_lift(_ buf: RustBuffer) throws -> DecodedImage {
    return try FfiConverterTypeDecodedImage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDecodedImage_lower(_ value: DecodedImage) -> RustBuffer {
    return FfiConverterTypeDecodedImage.lower(value)
}


public struct RgbaColor: Equatable, Hashable {
    public var r: Float
    public var g: Float
    public var b: Float
    public var a: Float

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(r: Float, g: Float, b: Float, a: Float) {
        self.r = r
        self.g = g
        self.b = b
        self.a = a
    }

    

    
}

#if compiler(>=6)
extension RgbaColor: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRgbaColor: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RgbaColor {
        return
            try RgbaColor(
                r: FfiConverterFloat.read(from: &buf), 
                g: FfiConverterFloat.read(from: &buf), 
                b: FfiConverterFloat.read(from: &buf), 
                a: FfiConverterFloat.read(from: &buf)
        )
    }

    public static func write(_ value: RgbaColor, into buf: inout [UInt8]) {
        FfiConverterFloat.write(value.r, into: &buf)
        FfiConverterFloat.write(value.g, into: &buf)
        FfiConverterFloat.write(value.b, into: &buf)
        FfiConverterFloat.write(value.a, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRgbaColor_lift(_ buf: RustBuffer) throws -> RgbaColor {
    return try FfiConverterTypeRgbaColor.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRgbaColor_lower(_ value: RgbaColor) -> RustBuffer {
    return FfiConverterTypeRgbaColor.lower(value)
}


/**
 * Flat render commands — Swift builds these, Rust draws them at absolute coordinates.
 * Describes a surface to composite onto the screen.
 */
public struct SurfaceDesc: Equatable, Hashable {
    public var surfaceId: UInt64
    public var x: Float
    public var y: Float
    public var width: Float
    public var height: Float
    public var cornerRadius: Float
    public var opacity: Float

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(surfaceId: UInt64, x: Float, y: Float, width: Float, height: Float, cornerRadius: Float, opacity: Float) {
        self.surfaceId = surfaceId
        self.x = x
        self.y = y
        self.width = width
        self.height = height
        self.cornerRadius = cornerRadius
        self.opacity = opacity
    }

    

    
}

#if compiler(>=6)
extension SurfaceDesc: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSurfaceDesc: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SurfaceDesc {
        return
            try SurfaceDesc(
                surfaceId: FfiConverterUInt64.read(from: &buf), 
                x: FfiConverterFloat.read(from: &buf), 
                y: FfiConverterFloat.read(from: &buf), 
                width: FfiConverterFloat.read(from: &buf), 
                height: FfiConverterFloat.read(from: &buf), 
                cornerRadius: FfiConverterFloat.read(from: &buf), 
                opacity: FfiConverterFloat.read(from: &buf)
        )
    }

    public static func write(_ value: SurfaceDesc, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.surfaceId, into: &buf)
        FfiConverterFloat.write(value.x, into: &buf)
        FfiConverterFloat.write(value.y, into: &buf)
        FfiConverterFloat.write(value.width, into: &buf)
        FfiConverterFloat.write(value.height, into: &buf)
        FfiConverterFloat.write(value.cornerRadius, into: &buf)
        FfiConverterFloat.write(value.opacity, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSurfaceDesc_lift(_ buf: RustBuffer) throws -> SurfaceDesc {
    return try FfiConverterTypeSurfaceDesc.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSurfaceDesc_lower(_ value: SurfaceDesc) -> RustBuffer {
    return FfiConverterTypeSurfaceDesc.lower(value)
}


/**
 * A surface's render commands bundled with its layout.
 */
public struct SurfaceFrame: Equatable, Hashable {
    public var desc: SurfaceDesc
    public var commands: [RenderCommand]
    /**
     * Pre-rendered BGRA8 pixel data from app-side rendering (legacy shm path).
     */
    public var pixelData: Data?
    /**
     * IOSurface ID for zero-copy GPU texture sharing.
     * When non-zero, the compositor imports this IOSurface directly —
     * no pixel upload or command rendering needed.
     */
    public var iosurfaceId: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(desc: SurfaceDesc, commands: [RenderCommand], 
        /**
         * Pre-rendered BGRA8 pixel data from app-side rendering (legacy shm path).
         */pixelData: Data?, 
        /**
         * IOSurface ID for zero-copy GPU texture sharing.
         * When non-zero, the compositor imports this IOSurface directly —
         * no pixel upload or command rendering needed.
         */iosurfaceId: UInt32) {
        self.desc = desc
        self.commands = commands
        self.pixelData = pixelData
        self.iosurfaceId = iosurfaceId
    }

    

    
}

#if compiler(>=6)
extension SurfaceFrame: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSurfaceFrame: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SurfaceFrame {
        return
            try SurfaceFrame(
                desc: FfiConverterTypeSurfaceDesc.read(from: &buf), 
                commands: FfiConverterSequenceTypeRenderCommand.read(from: &buf), 
                pixelData: FfiConverterOptionData.read(from: &buf), 
                iosurfaceId: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: SurfaceFrame, into buf: inout [UInt8]) {
        FfiConverterTypeSurfaceDesc.write(value.desc, into: &buf)
        FfiConverterSequenceTypeRenderCommand.write(value.commands, into: &buf)
        FfiConverterOptionData.write(value.pixelData, into: &buf)
        FfiConverterUInt32.write(value.iosurfaceId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSurfaceFrame_lift(_ buf: RustBuffer) throws -> SurfaceFrame {
    return try FfiConverterTypeSurfaceFrame.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSurfaceFrame_lower(_ value: SurfaceFrame) -> RustBuffer {
    return FfiConverterTypeSurfaceFrame.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum FontWeight: Equatable, Hashable {
    
    case ultraLight
    case thin
    case light
    case regular
    case medium
    case semibold
    case bold
    case heavy
    case black





}

#if compiler(>=6)
extension FontWeight: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFontWeight: FfiConverterRustBuffer {
    typealias SwiftType = FontWeight

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FontWeight {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .ultraLight
        
        case 2: return .thin
        
        case 3: return .light
        
        case 4: return .regular
        
        case 5: return .medium
        
        case 6: return .semibold
        
        case 7: return .bold
        
        case 8: return .heavy
        
        case 9: return .black
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FontWeight, into buf: inout [UInt8]) {
        switch value {
        
        
        case .ultraLight:
            writeInt(&buf, Int32(1))
        
        
        case .thin:
            writeInt(&buf, Int32(2))
        
        
        case .light:
            writeInt(&buf, Int32(3))
        
        
        case .regular:
            writeInt(&buf, Int32(4))
        
        
        case .medium:
            writeInt(&buf, Int32(5))
        
        
        case .semibold:
            writeInt(&buf, Int32(6))
        
        
        case .bold:
            writeInt(&buf, Int32(7))
        
        
        case .heavy:
            writeInt(&buf, Int32(8))
        
        
        case .black:
            writeInt(&buf, Int32(9))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFontWeight_lift(_ buf: RustBuffer) throws -> FontWeight {
    return try FfiConverterTypeFontWeight.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFontWeight_lower(_ value: FontWeight) -> RustBuffer {
    return FfiConverterTypeFontWeight.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Phosphor icon weight/style variant.
 */

public enum IconStyle: Equatable, Hashable {
    
    case regular
    case fill
    case duotone
    case thin
    case light
    case bold





}

#if compiler(>=6)
extension IconStyle: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeIconStyle: FfiConverterRustBuffer {
    typealias SwiftType = IconStyle

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> IconStyle {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .regular
        
        case 2: return .fill
        
        case 3: return .duotone
        
        case 4: return .thin
        
        case 5: return .light
        
        case 6: return .bold
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: IconStyle, into buf: inout [UInt8]) {
        switch value {
        
        
        case .regular:
            writeInt(&buf, Int32(1))
        
        
        case .fill:
            writeInt(&buf, Int32(2))
        
        
        case .duotone:
            writeInt(&buf, Int32(3))
        
        
        case .thin:
            writeInt(&buf, Int32(4))
        
        
        case .light:
            writeInt(&buf, Int32(5))
        
        
        case .bold:
            writeInt(&buf, Int32(6))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIconStyle_lift(_ buf: RustBuffer) throws -> IconStyle {
    return try FfiConverterTypeIconStyle.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIconStyle_lower(_ value: IconStyle) -> RustBuffer {
    return FfiConverterTypeIconStyle.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum RenderCommand: Equatable, Hashable {
    
    case rect(x: Float, y: Float, w: Float, h: Float, color: RgbaColor
    )
    case roundedRect(x: Float, y: Float, w: Float, h: Float, radius: Float, color: RgbaColor
    )
    case text(x: Float, y: Float, content: String, fontSize: Float, color: RgbaColor, weight: FontWeight, maxWidth: Float?, family: String?
    )
    /**
     * Render a Phosphor icon by name using SVG rasterization.
     */
    case icon(name: String, style: IconStyle, x: Float, y: Float, w: Float, h: Float, color: RgbaColor
    )
    case shadow(x: Float, y: Float, w: Float, h: Float, radius: Float, blur: Float, color: RgbaColor, ox: Float, oy: Float
    )
    case blurRect(x: Float, y: Float, w: Float, h: Float, radius: Float, blur: Float, tint: RgbaColor
    )
    case pushClip(x: Float, y: Float, w: Float, h: Float, radius: Float
    )
    case popClip
    case setOpacity(value: Float
    )
    case wallpaper(x: Float, y: Float, w: Float, h: Float
    )
    case image(textureId: UInt64, x: Float, y: Float, w: Float, h: Float
    )
    case registerTexture(textureId: UInt64, width: UInt32, height: UInt32, rgbaData: Data
    )
    case unregisterTexture(textureId: UInt64
    )





}

#if compiler(>=6)
extension RenderCommand: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRenderCommand: FfiConverterRustBuffer {
    typealias SwiftType = RenderCommand

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RenderCommand {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .rect(x: try FfiConverterFloat.read(from: &buf), y: try FfiConverterFloat.read(from: &buf), w: try FfiConverterFloat.read(from: &buf), h: try FfiConverterFloat.read(from: &buf), color: try FfiConverterTypeRgbaColor.read(from: &buf)
        )
        
        case 2: return .roundedRect(x: try FfiConverterFloat.read(from: &buf), y: try FfiConverterFloat.read(from: &buf), w: try FfiConverterFloat.read(from: &buf), h: try FfiConverterFloat.read(from: &buf), radius: try FfiConverterFloat.read(from: &buf), color: try FfiConverterTypeRgbaColor.read(from: &buf)
        )
        
        case 3: return .text(x: try FfiConverterFloat.read(from: &buf), y: try FfiConverterFloat.read(from: &buf), content: try FfiConverterString.read(from: &buf), fontSize: try FfiConverterFloat.read(from: &buf), color: try FfiConverterTypeRgbaColor.read(from: &buf), weight: try FfiConverterTypeFontWeight.read(from: &buf), maxWidth: try FfiConverterOptionFloat.read(from: &buf), family: try FfiConverterOptionString.read(from: &buf)
        )
        
        case 4: return .icon(name: try FfiConverterString.read(from: &buf), style: try FfiConverterTypeIconStyle.read(from: &buf), x: try FfiConverterFloat.read(from: &buf), y: try FfiConverterFloat.read(from: &buf), w: try FfiConverterFloat.read(from: &buf), h: try FfiConverterFloat.read(from: &buf), color: try FfiConverterTypeRgbaColor.read(from: &buf)
        )
        
        case 5: return .shadow(x: try FfiConverterFloat.read(from: &buf), y: try FfiConverterFloat.read(from: &buf), w: try FfiConverterFloat.read(from: &buf), h: try FfiConverterFloat.read(from: &buf), radius: try FfiConverterFloat.read(from: &buf), blur: try FfiConverterFloat.read(from: &buf), color: try FfiConverterTypeRgbaColor.read(from: &buf), ox: try FfiConverterFloat.read(from: &buf), oy: try FfiConverterFloat.read(from: &buf)
        )
        
        case 6: return .blurRect(x: try FfiConverterFloat.read(from: &buf), y: try FfiConverterFloat.read(from: &buf), w: try FfiConverterFloat.read(from: &buf), h: try FfiConverterFloat.read(from: &buf), radius: try FfiConverterFloat.read(from: &buf), blur: try FfiConverterFloat.read(from: &buf), tint: try FfiConverterTypeRgbaColor.read(from: &buf)
        )
        
        case 7: return .pushClip(x: try FfiConverterFloat.read(from: &buf), y: try FfiConverterFloat.read(from: &buf), w: try FfiConverterFloat.read(from: &buf), h: try FfiConverterFloat.read(from: &buf), radius: try FfiConverterFloat.read(from: &buf)
        )
        
        case 8: return .popClip
        
        case 9: return .setOpacity(value: try FfiConverterFloat.read(from: &buf)
        )
        
        case 10: return .wallpaper(x: try FfiConverterFloat.read(from: &buf), y: try FfiConverterFloat.read(from: &buf), w: try FfiConverterFloat.read(from: &buf), h: try FfiConverterFloat.read(from: &buf)
        )
        
        case 11: return .image(textureId: try FfiConverterUInt64.read(from: &buf), x: try FfiConverterFloat.read(from: &buf), y: try FfiConverterFloat.read(from: &buf), w: try FfiConverterFloat.read(from: &buf), h: try FfiConverterFloat.read(from: &buf)
        )
        
        case 12: return .registerTexture(textureId: try FfiConverterUInt64.read(from: &buf), width: try FfiConverterUInt32.read(from: &buf), height: try FfiConverterUInt32.read(from: &buf), rgbaData: try FfiConverterData.read(from: &buf)
        )
        
        case 13: return .unregisterTexture(textureId: try FfiConverterUInt64.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: RenderCommand, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .rect(x,y,w,h,color):
            writeInt(&buf, Int32(1))
            FfiConverterFloat.write(x, into: &buf)
            FfiConverterFloat.write(y, into: &buf)
            FfiConverterFloat.write(w, into: &buf)
            FfiConverterFloat.write(h, into: &buf)
            FfiConverterTypeRgbaColor.write(color, into: &buf)
            
        
        case let .roundedRect(x,y,w,h,radius,color):
            writeInt(&buf, Int32(2))
            FfiConverterFloat.write(x, into: &buf)
            FfiConverterFloat.write(y, into: &buf)
            FfiConverterFloat.write(w, into: &buf)
            FfiConverterFloat.write(h, into: &buf)
            FfiConverterFloat.write(radius, into: &buf)
            FfiConverterTypeRgbaColor.write(color, into: &buf)
            
        
        case let .text(x,y,content,fontSize,color,weight,maxWidth,family):
            writeInt(&buf, Int32(3))
            FfiConverterFloat.write(x, into: &buf)
            FfiConverterFloat.write(y, into: &buf)
            FfiConverterString.write(content, into: &buf)
            FfiConverterFloat.write(fontSize, into: &buf)
            FfiConverterTypeRgbaColor.write(color, into: &buf)
            FfiConverterTypeFontWeight.write(weight, into: &buf)
            FfiConverterOptionFloat.write(maxWidth, into: &buf)
            FfiConverterOptionString.write(family, into: &buf)
            
        
        case let .icon(name,style,x,y,w,h,color):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(name, into: &buf)
            FfiConverterTypeIconStyle.write(style, into: &buf)
            FfiConverterFloat.write(x, into: &buf)
            FfiConverterFloat.write(y, into: &buf)
            FfiConverterFloat.write(w, into: &buf)
            FfiConverterFloat.write(h, into: &buf)
            FfiConverterTypeRgbaColor.write(color, into: &buf)
            
        
        case let .shadow(x,y,w,h,radius,blur,color,ox,oy):
            writeInt(&buf, Int32(5))
            FfiConverterFloat.write(x, into: &buf)
            FfiConverterFloat.write(y, into: &buf)
            FfiConverterFloat.write(w, into: &buf)
            FfiConverterFloat.write(h, into: &buf)
            FfiConverterFloat.write(radius, into: &buf)
            FfiConverterFloat.write(blur, into: &buf)
            FfiConverterTypeRgbaColor.write(color, into: &buf)
            FfiConverterFloat.write(ox, into: &buf)
            FfiConverterFloat.write(oy, into: &buf)
            
        
        case let .blurRect(x,y,w,h,radius,blur,tint):
            writeInt(&buf, Int32(6))
            FfiConverterFloat.write(x, into: &buf)
            FfiConverterFloat.write(y, into: &buf)
            FfiConverterFloat.write(w, into: &buf)
            FfiConverterFloat.write(h, into: &buf)
            FfiConverterFloat.write(radius, into: &buf)
            FfiConverterFloat.write(blur, into: &buf)
            FfiConverterTypeRgbaColor.write(tint, into: &buf)
            
        
        case let .pushClip(x,y,w,h,radius):
            writeInt(&buf, Int32(7))
            FfiConverterFloat.write(x, into: &buf)
            FfiConverterFloat.write(y, into: &buf)
            FfiConverterFloat.write(w, into: &buf)
            FfiConverterFloat.write(h, into: &buf)
            FfiConverterFloat.write(radius, into: &buf)
            
        
        case .popClip:
            writeInt(&buf, Int32(8))
        
        
        case let .setOpacity(value):
            writeInt(&buf, Int32(9))
            FfiConverterFloat.write(value, into: &buf)
            
        
        case let .wallpaper(x,y,w,h):
            writeInt(&buf, Int32(10))
            FfiConverterFloat.write(x, into: &buf)
            FfiConverterFloat.write(y, into: &buf)
            FfiConverterFloat.write(w, into: &buf)
            FfiConverterFloat.write(h, into: &buf)
            
        
        case let .image(textureId,x,y,w,h):
            writeInt(&buf, Int32(11))
            FfiConverterUInt64.write(textureId, into: &buf)
            FfiConverterFloat.write(x, into: &buf)
            FfiConverterFloat.write(y, into: &buf)
            FfiConverterFloat.write(w, into: &buf)
            FfiConverterFloat.write(h, into: &buf)
            
        
        case let .registerTexture(textureId,width,height,rgbaData):
            writeInt(&buf, Int32(12))
            FfiConverterUInt64.write(textureId, into: &buf)
            FfiConverterUInt32.write(width, into: &buf)
            FfiConverterUInt32.write(height, into: &buf)
            FfiConverterData.write(rgbaData, into: &buf)
            
        
        case let .unregisterTexture(textureId):
            writeInt(&buf, Int32(13))
            FfiConverterUInt64.write(textureId, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRenderCommand_lift(_ buf: RustBuffer) throws -> RenderCommand {
    return try FfiConverterTypeRenderCommand.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRenderCommand_lower(_ value: RenderCommand) -> RustBuffer {
    return FfiConverterTypeRenderCommand.lower(value)
}



/**
 * Error type for the render FFI.
 */
public enum RenderError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case GpuInitFailed(reason: String
    )
    case RenderFailed(reason: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension RenderError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRenderError: FfiConverterRustBuffer {
    typealias SwiftType = RenderError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RenderError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .GpuInitFailed(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 2: return .RenderFailed(
            reason: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: RenderError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .GpuInitFailed(reason):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .RenderFailed(reason):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(reason, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRenderError_lift(_ buf: RustBuffer) throws -> RenderError {
    return try FfiConverterTypeRenderError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRenderError_lower(_ value: RenderError) -> RustBuffer {
    return FfiConverterTypeRenderError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionFloat: FfiConverterRustBuffer {
    typealias SwiftType = Float?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterFloat.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterFloat.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeRenderCommand: FfiConverterRustBuffer {
    typealias SwiftType = [RenderCommand]

    public static func write(_ value: [RenderCommand], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeRenderCommand.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [RenderCommand] {
        let len: Int32 = try readInt(&buf)
        var seq = [RenderCommand]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeRenderCommand.read(from: &buf))
        }
        return seq
    }
}
/**
 * Decode an image file (JPEG, PNG, GIF, BMP, etc.) to RGBA pixel data.
 */
public func decodeImage(data: Data)throws  -> DecodedImage  {
    return try  FfiConverterTypeDecodedImage_lift(try rustCallWithError(FfiConverterTypeRenderError_lift) {
    uniffi_clone_render_fn_func_decode_image(
        FfiConverterData.lower(data),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_clone_render_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_clone_render_checksum_func_decode_image() != 19939) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_render_checksum_method_apprenderer_iosurface_id() != 22375) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_render_checksum_method_apprenderer_mach_port() != 25689) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_render_checksum_method_apprenderer_mach_port_at() != 57815) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_render_checksum_method_apprenderer_render() != 42202) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_render_checksum_method_apprenderer_render_to_pixels() != 23673) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_render_checksum_method_apprenderer_render_to_pixels_transparent() != 5309) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_render_checksum_method_apprenderer_take_textures_changed() != 34270) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clone_render_checksum_constructor_apprenderer_new() != 17454) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureCloneRenderInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all